// decrypt_loader.cpp
//
// Native (JNI) side of the runtime loader. Responsibilities:
//   1. Read assets/logic.bin (passed in as raw bytes from Java —
//      Java owns AssetManager access, native code just gets the bytes)
//   2. AES-256-GCM decrypt it using a key embedded here
//   3. Return the decrypted dex bytes to Java as a jbyteArray, which
//      Java then hands to InMemoryDexClassLoader
//
// IMPORTANT — key handling:
// The AES key generated by encrypt_dex.py (build/dex_encryption_key.txt)
// must be pasted into AES_KEY below before building. This is the
// simplest possible approach (hardcoded key in native code) — it raises
// the bar versus a Java-visible key (native code is harder to
// decompile than Java/Kotlin bytecode) but is NOT secure against a
// determined attacker with tools like Frida or a native disassembler.
// This is appropriate for local/educational testing only.
//
// Build requires the Android NDK. See CMakeLists.txt in this folder.

#include <jni.h>
#include <openssl/evp.h>
#include <vector>
#include <cstring>
#include <android/log.h>

#define LOG_TAG "DecryptLoader"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

// PASTE THE HEX KEY FROM build/dex_encryption_key.txt HERE (64 hex chars = 32 bytes)
// Example placeholder below is NOT a real key — replace before building.
static const char *AES_KEY_HEX =
    "0000000000000000000000000000000000000000000000000000000000000000";

static const int KEY_SIZE_BYTES = 32; // AES-256
static const int IV_SIZE_BYTES = 12;  // GCM standard nonce size
static const int TAG_SIZE_BYTES = 16; // GCM auth tag size

// Convert the hex string above into raw key bytes once.
static bool hexToBytes(const char *hex, unsigned char *out, int outLen) {
    for (int i = 0; i < outLen; i++) {
        unsigned int byte;
        if (sscanf(hex + (i * 2), "%2x", &byte) != 1) {
            return false;
        }
        out[i] = (unsigned char) byte;
    }
    return true;
}

extern "C"
JNIEXPORT jbyteArray JNICALL
Java_com_android_pictach_loader_NativeLoader_decryptDex(
        JNIEnv *env, jobject /* this */, jbyteArray encryptedBlob) {

    unsigned char key[KEY_SIZE_BYTES];
    if (!hexToBytes(AES_KEY_HEX, key, KEY_SIZE_BYTES)) {
        LOGE("Failed to parse embedded AES key");
        return nullptr;
    }

    jsize blobLen = env->GetArrayLength(encryptedBlob);
    if (blobLen < IV_SIZE_BYTES + TAG_SIZE_BYTES) {
        LOGE("Encrypted blob too small: %d bytes", blobLen);
        return nullptr;
    }

    jbyte *blobBytes = env->GetByteArrayElements(encryptedBlob, nullptr);

    // Layout written by encrypt_dex.py: [IV][ciphertext][TAG]
    const unsigned char *iv = reinterpret_cast<unsigned char *>(blobBytes);
    int ciphertextLen = blobLen - IV_SIZE_BYTES - TAG_SIZE_BYTES;
    const unsigned char *ciphertext =
            reinterpret_cast<unsigned char *>(blobBytes) + IV_SIZE_BYTES;
    const unsigned char *tag =
            reinterpret_cast<unsigned char *>(blobBytes) + IV_SIZE_BYTES + ciphertextLen;

    std::vector<unsigned char> plaintext(ciphertextLen);
    int outLen = 0;
    bool success = false;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (ctx != nullptr) {
        if (EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), nullptr, nullptr, nullptr) == 1 &&
            EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, IV_SIZE_BYTES, nullptr) == 1 &&
            EVP_DecryptInit_ex(ctx, nullptr, nullptr, key, iv) == 1) {

            int len1 = 0;
            if (EVP_DecryptUpdate(ctx, plaintext.data(), &len1, ciphertext, ciphertextLen) == 1) {
                outLen = len1;

                // Set expected tag value before final call
                if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, TAG_SIZE_BYTES,
                                         (void *) tag) == 1) {
                    int len2 = 0;
                    int finalRet = EVP_DecryptFinal_ex(ctx, plaintext.data() + len1, &len2);
                    if (finalRet == 1) {
                        outLen += len2;
                        success = true;
                    } else {
                        LOGE("GCM tag verification failed — blob may be corrupted or tampered");
                    }
                }
            }
        }
        EVP_CIPHER_CTX_free(ctx);
    }

    env->ReleaseByteArrayElements(encryptedBlob, blobBytes, JNI_ABORT);

    if (!success) {
        LOGE("Decryption failed");
        return nullptr;
    }

    LOGI("Decrypted %d bytes successfully", outLen);

    jbyteArray result = env->NewByteArray(outLen);
    env->SetByteArrayRegion(result, 0, outLen,
                             reinterpret_cast<jbyte *>(plaintext.data()));
    return result;
}
